version: "3.9"

services:
  postgres:
    image: postgres:15.3-alpine
    hostname: ${DATABASE_HOST}
    command: -p ${DATABASE_PORT} # Change the default port
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "${DATABASE_PORT}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always
    volumes:
      - airplane-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    # volumes:
    #   - airplane-pgadmin:/var/lib/pgadmin

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "./wait-for-it.sh ${DATABASE_HOST}:${DATABASE_PORT} -- ./main"
    depends_on:
      - postgres
    hostname: backend
    working_dir: /root/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - "8080:8080"
      # - "8081:8081"
    # volumes:
    #   - airplane-backend:/root/

  # proxy:
  #   image: nginx
  #   volumes:
  #     - type: bind
  #       source: ./proxy/nginx.conf
  #       target: /etc/nginx/conf.d/default.conf
  #       read_only: true
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend

volumes:
  airplane-postgres:
#   airplane-pgadmin:
#   airplane-backend:
